CURRENT_SERVER_NAME= 'YOUR_SERVER_NAME'
APPLICATION_ID = 'YOUR_APP_ID'
REST_API_KEY = 'YOUR_REST_API_KEY'
MASTER_KEY = 'YOUR_MASTER_KEY'
PARSE_SERVER_URI = "YOUR_PARSE_SERVER_URI"
LOG_PATH = 'imdb_server.log'
SINGLE_TEST_MODE = False # whether only for testing single movie per task